[theme]
# Primary accent color for interactive elements.
primaryColor = "#6fa8dc"

# Background color for the main content area.
backgroundColor = "#eeeeee"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#0083B8"

# Color used for almost all text.
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
